//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webxml.zhaoqi.vip/", ConfigurationName="ServiceReference1.NoticeSoap")]
    public interface NoticeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.zhaoqi.vip/getSupportDep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getSupportDep();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.zhaoqi.vip/getNoticeByDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDemo.ServiceReference1.Message[] getNoticeByDepartment(string dep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.zhaoqi.vip/getNoticeByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDemo.ServiceReference1.Message[] getNoticeByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.zhaoqi.vip/getNoticeByDepartmentAndDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDemo.ServiceReference1.Message[] getNoticeByDepartmentAndDate(string dep, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webxml.zhaoqi.vip/getNoticeByLikeTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDemo.ServiceReference1.Message[] getNoticeByLikeTitle(string keyword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webxml.zhaoqi.vip/")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string linkField;
        
        private System.DateTime dateField;
        
        private string typeField;
        
        private string departmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoticeSoapChannel : WebServiceDemo.ServiceReference1.NoticeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoticeSoapClient : System.ServiceModel.ClientBase<WebServiceDemo.ServiceReference1.NoticeSoap>, WebServiceDemo.ServiceReference1.NoticeSoap {
        
        public NoticeSoapClient() {
        }
        
        public NoticeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoticeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoticeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoticeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getSupportDep() {
            return base.Channel.getSupportDep();
        }
        
        public WebServiceDemo.ServiceReference1.Message[] getNoticeByDepartment(string dep) {
            return base.Channel.getNoticeByDepartment(dep);
        }
        
        public WebServiceDemo.ServiceReference1.Message[] getNoticeByDate(string date) {
            return base.Channel.getNoticeByDate(date);
        }
        
        public WebServiceDemo.ServiceReference1.Message[] getNoticeByDepartmentAndDate(string dep, string date) {
            return base.Channel.getNoticeByDepartmentAndDate(dep, date);
        }
        
        public WebServiceDemo.ServiceReference1.Message[] getNoticeByLikeTitle(string keyword) {
            return base.Channel.getNoticeByLikeTitle(keyword);
        }
    }
}
